### ISSUE TITLE
qrcodejs2生成二维码自适应

### ISSUE THREAD

**Issue by hsingyin** [hsingyin/hsingyin.site#4]
展码这样的需求场景十分常见，在二维码生成之后需要根据移动设备的宽高写自适应。但是问题来了，使用到的qrcodejs2，构造函数传入的宽高不是rem这样的单位。canvas的画布大小是固定的。为此使用曲线救国在生成二维码的节点下加入important样式。
```css       
 img,
 canvas {
     width: 3.8rem !important;
     height: 3.8rem !important;
 }
```
这样就可以实现二维码的自适应。
